server:
  port: 0

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/main
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: userservice
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

    instances:
      eventServiceCircuitBreaker:
        base-config: default

management:
  endpoints:
    web:
      exposure:
        include: "env,configprops,health"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}