CREATE SCHEMA IF NOT EXISTS userservice;
SET search_path TO userservice;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE
);

-- Индекс для поиска по email
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);