CREATE SCHEMA IF NOT EXISTS requestservice;
SET search_path TO requestservice;

CREATE TABLE IF NOT EXISTS participation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_participation_requests_event ON participation_requests(event_id);
CREATE INDEX IF NOT EXISTS idx_participation_requests_requester ON participation_requests(requester_id);
CREATE INDEX IF NOT EXISTS idx_participation_requests_status ON participation_requests(status);
CREATE INDEX IF NOT EXISTS idx_participation_requests_event_requester ON participation_requests(event_id, requester_id);