server:
  port: 9095

spring:
  application:
    name: aggregator
  cloud:
    config:
      enabled: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: aggregator-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.practicum.ewm.stats.kafka.AvroDeserializer
      properties:
        value.deserializer.target.type: ru.practicum.ewm.stats.avro.UserActionAvro
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 500
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.practicum.ewm.stats.kafka.AvroSerializer
      properties:
        acks: all
        retries: 3
        batch.size: 16384

aggregator:
  kafka:
    producer:
      topic: stats.events-similarity.v1
      properties:
        compression.type: snappy
        linger.ms: 10
    consumer:
      topic: stats.user-actions.v1
      poll-timeout: 100ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: false

logging:
  level:
    ru.practicum.ewm.stats.aggregator: DEBUG