syntax = "proto3";

package stats.service.dashboard;

message InteractionsCountRequestProto {
  repeated int64 event_id = 1;
}

message RecommendedEventProto {
  int64 event_id = 1;
  double score = 2;
}

service RecommendationsController {
   rpc GetRecommendationsForUser(UserPredictionsRequestProto) returns (stream RecommendedEventProto);
   rpc GetSimilarEvents(SimilarEventsRequestProto) returns (stream RecommendedEventProto);
   rpc GetInteractionsCount(InteractionsCountRequestProto) returns (stream RecommendedEventProto);
}