server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        # ======================= ФЕЙН-ЗАПРОСЫ =======================
        - id: feign_event_route
          uri: lb://event-service
          predicates:
            - Path=/events/feign/**

        - id: feign_request_route
          uri: lb://request-service
          predicates:
            - Path=/requests/feign/**

        - id: feign_user_route
          uri: lb://user-service
          predicates:
            - Path=/users/feign/**

        - id: feign_comment_route
          uri: lb://comment-service
          predicates:
            - Path=/comments/feign/**

        # ======================= КОММЕНТАРИИ =======================
        - id: private_user_event_comments_route
          uri: lb://comment-service
          predicates:
            - Path=/users/{userId}/comments/event/{eventId}
            - Method=POST

        - id: private_user_comments_with_id_route
          uri: lb://comment-service
          predicates:
            - Path=/users/{userId}/comments/{commentId}
            - Method=GET,PATCH,DELETE

        - id: private_user_comments_route
          uri: lb://comment-service
          predicates:
            - Path=/users/{userId}/comments
            - Method=GET

        - id: public_comments_event_route
          uri: lb://comment-service
          predicates:
            - Path=/comments/event/{eventId}
            - Method=GET

        - id: public_comments_id_route
          uri: lb://comment-service
          predicates:
            - Path=/comments/{commentId}
            - Method=GET

        # ======================= АДМИН =======================
        - id: admin_users_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: admin_categories_route
          uri: lb://event-service
          predicates:
            - Path=/admin/categories/**

        - id: admin_events_route
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**

        - id: admin_compilations_route
          uri: lb://event-service
          predicates:
            - Path=/admin/compilations/**

        - id: admin_comments_route
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**

        # ======================= ПРИВАТНЫЕ =======================
        - id: private_event_requests_route
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/events/{eventId}/requests
            - Method=GET,PATCH

        - id: private_user_events_with_id_route
          uri: lb://event-service
          predicates:
            - Path=/users/{userId}/events/{eventId}
            - Method=GET,PATCH

        - id: private_user_events_route
          uri: lb://event-service
          predicates:
            - Path=/users/{userId}/events
            - Method=GET,POST

        - id: private_user_requests_with_id_route
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/{requestId}/cancel
            - Method=PATCH

        - id: private_user_requests_route
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests
            - Method=GET,POST

        # ======================= ПУБЛИЧНЫЕ =======================
        - id: public_categories_route
          uri: lb://event-service
          predicates:
            - Path=/categories/**
            - Method=GET

        - id: public_compilations_route
          uri: lb://event-service
          predicates:
            - Path=/compilations/**
            - Method=GET

        - id: public_events_route
          uri: lb://event-service
          predicates:
            - Path=/events/**
            - Method=GET

        # ======================= СТАТИСТИКА =======================
        - id: stats_hit_route
          uri: lb://stats-server
          predicates:
            - Path=/hit
            - Method=POST

        - id: stats_get_route
          uri: lb://stats-server
          predicates:
            - Path=/stats
            - Method=GET

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: TRACE
    org.springframework.cloud.gateway.handler.FilteringWebHandler: TRACE
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG