server:
  port: 8082

spring:
  application:
    name: event-service

  datasource:
    url: jdbc:postgresql://localhost:6542/main
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: eventservice

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  jackson:
    time-zone: UTC

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      user-service:
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
      request-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
      comment-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
  config:
    instance:
      user-service:
        baseConfig: default
      request-service:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: "env,configprops,health"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    ru.practicum: DEBUG
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    okhttp3: DEBUG
    org.apache.http.wire: DEBUG